import { Layout } from "Client/Component/Layout/Index";
import { Container } from "Client/Component/UI/Container";

const NAMES: { ar: string; en: string; meaning: string }[] = [
  { ar: "اللَّه", en: "Allah", meaning: "The Greatest Name" },
  { ar: "الرَّحْمَن", en: "Ar-Rahman", meaning: "The Most Compassionate" },
  { ar: "الرَّحِيم", en: "Ar-Rahim", meaning: "The Most Merciful" },
  { ar: "الْمَلِك", en: "Al-Malik", meaning: "The King" },
  { ar: "الْقُدُّوس", en: "Al-Quddus", meaning: "The Most Holy" },
  { ar: "السَّلَام", en: "As-Salam", meaning: "The Source of Peace" },
  { ar: "الْمُؤْمِن", en: "Al-Mu'min", meaning: "The Giver of Faith" },
  { ar: "الْمُهَيْمِن", en: "Al-Muhaymin", meaning: "The Guardian" },
  { ar: "الْعَزِيز", en: "Al-Aziz", meaning: "The Almighty" },
  { ar: "الْجَبَّار", en: "Al-Jabbar", meaning: "The Compeller" },
  { ar: "الْمُتَكَبِّر", en: "Al-Mutakabbir", meaning: "The Supreme" },
  { ar: "الْخَالِق", en: "Al-Khaliq", meaning: "The Creator" },
  { ar: "الْبَارِئ", en: "Al-Bari'", meaning: "The Evolver" },
  { ar: "الْمُصَوِّر", en: "Al-Musawwir", meaning: "The Fashioner" },
  { ar: "الْغَفَّار", en: "Al-Ghaffar", meaning: "The Constant Forgiver" },
  { ar: "الْقَهَّار", en: "Al-Qahhar", meaning: "The Subduer" },
  { ar: "الْوَهَّاب", en: "Al-Wahhab", meaning: "The Bestower" },
  { ar: "الرَّزَّاق", en: "Ar-Razzaq", meaning: "The Provider" },
  { ar: "الْفَتَّاح", en: "Al-Fattah", meaning: "The Opener" },
  { ar: "الْعَلِيم", en: "Al-'Alim", meaning: "The All-Knowing" },
  { ar: "الْقَابِض", en: "Al-Qabid", meaning: "The Withholder" },
  { ar: "الْبَاسِط", en: "Al-Basit", meaning: "The Extender" },
  { ar: "الْخَافِض", en: "Al-Khafid", meaning: "The Abaser" },
  { ar: "الرَّافِع", en: "Ar-Rafi'", meaning: "The Exalter" },
  { ar: "الْمُعِزّ", en: "Al-Mu'izz", meaning: "The Honourer" },
  { ar: "الْمُذِلّ", en: "Al-Mudhill", meaning: "The Humiliator" },
  { ar: "السَّمِيع", en: "As-Sami'", meaning: "The All-Hearing" },
  { ar: "الْبَصِير", en: "Al-Basir", meaning: "The All-Seeing" },
  { ar: "الْحَكَم", en: "Al-Hakam", meaning: "The Judge" },
  { ar: "الْعَدْل", en: "Al-'Adl", meaning: "The Utterly Just" },
  { ar: "اللَّطِيف", en: "Al-Latif", meaning: "The Subtly Kind" },
  { ar: "الْخَبِير", en: "Al-Khabir", meaning: "The All-Aware" },
  { ar: "الْحَلِيم", en: "Al-Halim", meaning: "The Forbearing" },
  { ar: "الْعَظِيم", en: "Al-'Azim", meaning: "The Magnificent" },
  { ar: "الْغَفُور", en: "Al-Ghafur", meaning: "The Forgiving" },
  { ar: "الشَّكُور", en: "Ash-Shakur", meaning: "The Appreciative" },
  { ar: "الْعَلِيّ", en: "Al-'Aliyy", meaning: "The Most High" },
  { ar: "الْكَبِير", en: "Al-Kabir", meaning: "The Most Great" },
  { ar: "الْحَفِيظ", en: "Al-Hafiz", meaning: "The Preserver" },
  { ar: "الْمُقِيت", en: "Al-Muqit", meaning: "The Sustainer" },
  { ar: "الْحَسِيب", en: "Al-Hasib", meaning: "The Reckoner" },
  { ar: "الْجَلِيل", en: "Al-Jalil", meaning: "The Majestic" },
  { ar: "الْكَرِيم", en: "Al-Karim", meaning: "The Most Generous" },
  { ar: "الرَّقِيب", en: "Ar-Raqib", meaning: "The Watchful" },
  { ar: "الْمُجِيب", en: "Al-Mujib", meaning: "The Responsive" },
  { ar: "الْوَاسِع", en: "Al-Wasi'", meaning: "The All-Encompassing" },
  { ar: "الْحَكِيم", en: "Al-Hakim", meaning: "The All-Wise" },
  { ar: "الْوَدُود", en: "Al-Wadud", meaning: "The Most Loving" },
  { ar: "الْمَجِيد", en: "Al-Majid", meaning: "The Most Glorious" },
  { ar: "الْبَاعِث", en: "Al-Ba'ith", meaning: "The Resurrector" },
  { ar: "الشَّهِيد", en: "Ash-Shahid", meaning: "The Witness" },
  { ar: "الْحَقّ", en: "Al-Haqq", meaning: "The Absolute Truth" },
  { ar: "الْوَكِيل", en: "Al-Wakil", meaning: "The Trustee" },
  { ar: "الْقَوِيّ", en: "Al-Qawiyy", meaning: "The All-Strong" },
  { ar: "الْمَتِين", en: "Al-Matin", meaning: "The Firm" },
  { ar: "الْوَلِيّ", en: "Al-Waliyy", meaning: "The Protecting Friend" },
  { ar: "الْحَمِيد", en: "Al-Hamid", meaning: "The All-Praiseworthy" },
  { ar: "الْمُحْصِي", en: "Al-Muhsi", meaning: "The All-Enumerating" },
  { ar: "الْمُبْدِئ", en: "Al-Mubdi'", meaning: "The Originator" },
  { ar: "الْمُعِيد", en: "Al-Mu'id", meaning: "The Restorer" },
  { ar: "الْمُحْيِي", en: "Al-Muhyi", meaning: "The Giver of Life" },
  { ar: "الْمُمِيت", en: "Al-Mumit", meaning: "The Bringer of Death" },
  { ar: "الْحَيّ", en: "Al-Hayy", meaning: "The Ever-Living" },
  { ar: "الْقَيُّوم", en: "Al-Qayyum", meaning: "The Self-Subsisting" },
  { ar: "الْوَاجِد", en: "Al-Wajid", meaning: "The Perceiver" },
  { ar: "الْمَاجِد", en: "Al-Majid", meaning: "The Illustrious" },
  { ar: "الْوَاحِد", en: "Al-Wahid", meaning: "The One" },
  { ar: "الْأَحَد", en: "Al-Ahad", meaning: "The Unique" },
  { ar: "الصَّمَد", en: "As-Samad", meaning: "The Eternal" },
  { ar: "الْقَادِر", en: "Al-Qadir", meaning: "The Capable" },
  { ar: "الْمُقْتَدِر", en: "Al-Muqtadir", meaning: "The Powerful" },
  { ar: "الْمُقَدِّم", en: "Al-Muqaddim", meaning: "The Expediter" },
  { ar: "الْمُؤَخِّر", en: "Al-Mu'akhkhir", meaning: "The Delayer" },
  { ar: "الْأَوَّل", en: "Al-Awwal", meaning: "The First" },
  { ar: "الْآخِر", en: "Al-Akhir", meaning: "The Last" },
  { ar: "الظَّاهِر", en: "Az-Zahir", meaning: "The Manifest" },
  { ar: "الْبَاطِن", en: "Al-Batin", meaning: "The Hidden" },
  { ar: "الْوَالِي", en: "Al-Wali", meaning: "The Governor" },
  { ar: "الْمُتَعَالِي", en: "Al-Muta'ali", meaning: "The Self-Exalted" },
  { ar: "الْبَرّ", en: "Al-Barr", meaning: "The Source of Goodness" },
  { ar: "التَّوَّاب", en: "At-Tawwab", meaning: "The Acceptor of Repentance" },
  { ar: "الْمُنْتَقِم", en: "Al-Muntaqim", meaning: "The Avenger" },
  { ar: "الْعَفُوّ", en: "Al-'Afuww", meaning: "The Pardoner" },
  { ar: "الرَّؤُوف", en: "Ar-Ra'uf", meaning: "The Most Kind" },
  { ar: "مَالِكُ الْمُلْك", en: "Malik-ul-Mulk", meaning: "Owner of the Kingdom" },
  { ar: "ذُو الْجَلَالِ وَالْإِكْرَام", en: "Dhul-Jalali wal-Ikram", meaning: "Lord of Majesty & Honour" },
  { ar: "الْمُقْسِط", en: "Al-Muqsit", meaning: "The Equitable" },
  { ar: "الْجَامِع", en: "Al-Jami'", meaning: "The Gatherer" },
  { ar: "الْغَنِيّ", en: "Al-Ghaniyy", meaning: "The Self-Sufficient" },
  { ar: "الْمُغْنِي", en: "Al-Mughni", meaning: "The Enricher" },
  { ar: "الْمَانِع", en: "Al-Mani'", meaning: "The Withholder" },
  { ar: "الضَّارّ", en: "Ad-Darr", meaning: "The Distresser" },
  { ar: "النَّافِع", en: "An-Nafi'", meaning: "The Benefactor" },
  { ar: "النُّور", en: "An-Nur", meaning: "The Light" },
  { ar: "الْهَادِي", en: "Al-Hadi", meaning: "The Guide" },
  { ar: "الْبَدِيع", en: "Al-Badi'", meaning: "The Originator" },
  { ar: "الْبَاقِي", en: "Al-Baqi", meaning: "The Everlasting" },
  { ar: "الْوَارِث", en: "Al-Warith", meaning: "The Inheritor" },
  { ar: "الرَّشِيد", en: "Ar-Rashid", meaning: "The Guide to Right Path" },
  { ar: "الصَّبُور", en: "As-Sabur", meaning: "The Patient" },
];

export default function Names() {
  return (
    <Layout>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
        {NAMES.map((n, i) => (
          <Container key={n.en + i} className="!p-4 text-center">
            <p className="text-xs text-muted-foreground">{i + 1}</p>
            <p className="text-2xl font-arabic mt-1" dir="rtl">{n.ar}</p>
            <p className="font-semibold mt-2">{n.en}</p>
            <p className="text-xs text-muted-foreground">{n.meaning}</p>
          </Container>
        ))}
      </div>
    </Layout>
  );
}
